### ISSUE TITLE
Doesn't build on Windows ARM64

### ISSUE THREAD

**Issue by zhihaoy** [decathorpe/mitmproxy_wireguard#24]
Would you consider patching the `ring` package locally for this Python package?
The upstream made no progress after a few months.

See also: https://github.com/briansmith/ring/issues/1514#issuecomment-1258562375

**Comment by decathorpe** [comment]
Sorry, I'm not comfortable with applying random patches to crypto libraries ... I know that development of "ring" is not always reliable, but I'd rather wait until there's an official released version of the fix that we can use (or rather, that boringtun can start to use, since mitmproxy_wireguard doesn't depend on ring directly).

**Comment by mhils** [comment]
Strong :+1: on waiting for an official release.
