### ISSUE TITLE
`pip install --no-binary :all: mitmproxy-wireguard` fails

### ISSUE THREAD

**Issue by mhils** [decathorpe/mitmproxy_wireguard#25]
https://crates.io/crates/x25519-dalek has recently shipped `v2.0.0-rc.2`, which includes a breaking change over the previous `v2.0.0-pre.1` release. This causes `pip install --no-binary :all: mitmproxy-wireguard` to fail (see https://github.com/mitmproxy/mitmproxy/discussions/6045). Things seem to work for mitmproxy_rs because the sdist there includes Cargo.lock (and that is somehow take into account I guess), but it fails for `mitmproxy-wireguard`. Can we ship a quick patch release including Cargo.lock? :)

**Comment by decathorpe** [comment]
Huh, I'm not sure why the sdist doesn't include the `Cargo.lock` file ... I assumed it was included.

Looks like this is a known limitation of cargo / maturin:
https://github.com/PyO3/maturin/discussions/748#discussioncomment-1839933

Anyway, since `v2.0.0-rc.2` is not compatible with `v2.0.0-pre.1`, we need to pin to the latter anyway, so I'll do that, include `Cargo.lock` explicitly in the sdist, and publish a new release.

**Comment by decathorpe** [comment]
Should be fixed with v0.1.23:
https://pypi.org/project/mitmproxy-wireguard/0.1.23/
